# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get -y install gcc-avr binutils-avr avr-libc
  displayName: 'get avr tools'

- script: make
  displayName: 'build'

- script: mkdir $(Pipeline.Workspace)/bin; cp Joystick.elf $(Pipeline.Workspace)/bin/
  displayName: 'copy binary to /bin'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/bin'
    artifact: 'build'
    publishLocation: 'pipeline'
  displayName: 'publish binary'
